apiVersion: apps/v1
kind: Deployment
metadata:
  name: myrun-frontend
  labels:
    app: myrun-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myrun-frontend
  template:
    metadata:
      labels:
        app: myrun-frontend
    spec:
      containers:
        - name: myrun-container
          image: min02jin/myrun-frondend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"