apiVersion: v1
kind: Service
metadata:
  name: myrun-frontend-service
spec:
  type: ClusterIP
  clusterIP: 10.96.204.149
  selector:
    app: myrun-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000