apiVersion: apps/v1
kind: Deployment
metadata:
  name: myrun-backend
  labels:
    app: myrun-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myrun-backend
  template:
    metadata:
      labels:
        app: myrun-backend
        tier: backend
    spec:
      containers:
        - name: myrun-backend
          image: sje21/myrun-backend:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              value: "4000"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: myrun-mysql-config
                  key: MYSQL_HOST
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: myrun-mysql-config
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: myrun-mysql-secret
                  key: MYSQL_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: myrun-mysql-config
                  key: MYSQL_DATABASE
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: myrun-backend
spec:
  selector:
    app: myrun-backend
  ports:
    - port: 4000
      targetPort: 4000
  type: ClusterIP
