apiVersion: apps/v1
kind: Deployment
metadata:
  name: myrun-frontend
  labels:
    app: myrun-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myrun-frontend
  template:
    metadata:
      labels:
        app: myrun-frontend
        tier: frontend
    spec:
      containers:
        - name: myrun-frontend
          image: sje21/myrun-frontend:v1
          imagePullPolicy: Always
          
          ports:
            - containerPort: 3000 
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
      
---
apiVersion: v1
kind: Service
metadata:
  name: myrun-frontend
spec:
  selector:
    app: myrun-frontend
  ports:
    - port: 3000
      targetPort: 3000
  type: NodePort